configs/config.yaml
core/compliance_mappings/orchestrator.py
core/runner.py
core/test_engine/orchestrator.py

- working e2e nist compliance report generation. Working for report gen.
- [WIP]: NIST Control => strategy mapping, 
- [WIP]: failure => control mapping, 
- [WIP]: enriching results 
- [WIP]: meaningful documentation

working nist compliance report generation

---

README.md

1. Read me to add contributions
2. Icons
3. Detailed docs view

chore: made readme better

---

README.md
cli/commands.py
cli/main.py
docs/installation.md
docs/quickstart.md
pyproject.toml

Adds the cli to pyproject.toml to make it installable
Turns the current commands into CLI sub-commands under compliant-llm
Updates docs to reflect this

make compliant-llm installable and executable

---

README.md
configs/config.yaml
core/compliance_mappings/nist/adapter.py
core/providers/litellm_provider.py
core/runner.py
core/test_engine/orchestrator.py
docs/cli/config.md
docs/index.md
docs/locked.md
tests/test_runner.py

- Added locked in features, could be a separate doc with partial images of internal dashboard.

raising next set of features

---

docs/README.md
docs/release_guide.md

define the process to do a pre-release and a full release

add a release guide

---

cli/commands.py
cli/main.py

implements `compliant-llm --version`

print the version of compliant-llm

---

README.md
cli/commands.py
core/config_manager/cli_adapter.py
core/config_manager/config.py
core/reporter.py
core/runner.py
docs/configuration.md

- added consistent time stamp for report files `report_file_name_{timestamp}.json`
- fixed documentation
- fixed saving reports twice error
- added report_metadata to file
-

added timestamp to output file names

---

core/config_manager/ui_adapter.py
ui/app.py
ui/components/compliance_report.py
ui/components/security_findings.py
ui/dashboard.py

working app dashboard, new graphs for compliance

---

core/config_manager/cli_adapter.py
core/config_manager/config.py
core/config_manager/ui_adapter.py
ui/dashboard.py

using the path /.compliant-llm/reports/ for storing reports this is for consistency across systems
note: this needs to be managed in the docker container as well

update report directory to a hidden folder in user home

---

cli/commands.py

- remove dead code
- fix comments

Chore/clean code - remove dead code

---

ui/app.py
ui/components/security_findings.py
ui/dashboard.py

1. You can view the latest report after tests have ran
2. Optimise port code
3. Also github template is working now
**Checklist**

chore: Show latest report after test completion

---

README.md

chore: add gif instead

---

core/evaluators/evals/attack_evaluator.py
core/providers/litellm_provider.py
core/strategies/attack_strategies/data_poisoning/base.py
core/strategies/attack_strategies/excessive_agency/base.py
core/strategies/attack_strategies/indirect_prompt_injection/base.py
core/strategies/attack_strategies/jailbreak/data.yaml
core/strategies/attack_strategies/prompt_injection/data.yaml
core/strategies/attack_strategies/sensitive_info_disclosure/base.py

fixed evals, prompts and llm cleaning

---

README.md
docs/README.md
docs/configuration.md
docs/getting_started.md
docs/installation.md
docs/quickstart.md

Updates the docs and removes incorrect details.
Adds azure documentation to the docs
**Checklist**

Documentation update

---

README.md

- add an interactive star widget
- displays star count
- stars repo on click
- displayed below the top banner
**Checklist**

add an interactive star widget

---

README.md

revert stars related change to readme

---

README.md

- Adds a support section to the README
**Checklist**

Add support to README.md

---

configs/config.yaml
core/config_manager/cli_adapter.py
core/config_manager/config.py
core/config_manager/ui_adapter.py
core/evaluators/base.py
core/providers/litellm_provider.py
core/runner.py
ui/constants/provider.py
ui/dashboard.py

- working cli, ui and config path with Azure. 
-  Need to test with OpenAI thoroughly again.
- Rerun might break -- but its not exposed yet.
- Integrating Azure with UI was broken.
UI
Config
CLI
**Checklist**

Working Azure Integration

---

pyproject.toml

- v0.4.1-rc1 pre-release
**Checklist**

pre-release 0.4.1-rc1

---

pyproject.toml

release v0.1.5

---

pyproject.toml

Pre-release v0.1.6-alpha1 will deploy compliant-llm to TestPypi.
**Checklist**

pre-release v0.1.6-alpha1

---

pyproject.toml

Release v0.1.6 to pypi
**Checklist**

release v0.1.6

---

.github/ISSUE_TEMPLATE/feature_request.md

Add a use case section to new feature requests
**Checklist**

update new feature template

---

core/analytics/tracker.py
core/providers/litellm_provider.py

1. LiteLLM is showing unnecessary Logs 
2. Moved @kaushik-himself 's azure log code to this PR
**Checklist**

chore: remove logging from litellm

---

pyproject.toml

pre-release v0.1.7-alpha1

---

pyproject.toml

Release v0.1.8-alpha1

---

pyproject.toml

pre-release 0.1.9-alpha1

---

pyproject.toml

release 0.1.9
